### ISSUE TITLE
White Screen Simulator Crash Bug

### ISSUE THREAD

**Issue by Wertyuui345** [chiragsakhuja/lc3tools#15] opened 2020-10-19 18:45 UTC
On occasion, after simulating code in lc3tools, the simulator will "crash", showing a white screen. The only way that I've been able to fix it is by hitting View -> Reload or by exiting out of the program itself. While it doesn't delete the loaded code, it forces users to open the code file every single time it occurs, which becomes tedious.

I found that this bug frequently happens after pressing "Reinitializing Machine," but it isn't limited to that button. The issue, while it may appear to clear up on its own on the video, will not clear up until after you reload or exit and re-enter the program. Light and Dark themes don't affect the crash as far as I can tell. 

It also seems to worsen when code becomes larger and larger, possibly due to the increasing number of instructions needed to run through. Running the simulator without code doesn't seem to replicate the problem.

Video Demonstration:
[https://drive.google.com/file/d/12L6gj4hBukc4liQ3bah1fW5LIre4VBAp/view?usp=sharing](url)

**Comment by chiragsakhuja** [comment] 2021-01-09 00:40
Thanks for pointing out this bug.  This crash was due to a segfault in the C++ backend, which is why it required restarting or reloading the application.  Unfortunately I was never able to reproduce on any of my machines.

I've rewritten the entire simulator backend to be more stable and deterministic.  Currently it lives on the `framework2` branch, but it will be moved to `master` in the next couple of days.  There will also be a corresponding GUI release on Github.

I don't believe this issue will arise in future releases, so I'm closing this issue for now.  If it does end up persisting, I'll reopen.

**Closed by chiragsakhuja** 2021-01-09 00:40 UTC
